- .releaserc
- .secrets.baseline
- examples/ibm-catalog/prepared-system-solution/catalogValidationValues.json.template
add required changes for catalog publish / validation. Note the validation will not yet work because we need to find a way to pass private key to pipeline
> ci: changes for catalog validation

- .github/settings.yml
Adds the repo name and description properties and values. 
See related [PR for infrastructure](https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure/pull/109)
> Set repo name and description

- ibm_catalog.json
This is a change to update the catalog json file to use the newer schema published and pushed to prod on 10/31.  No new function add here.  The main reason to do this is so that all of the repos that have a catalog json file are using the same schema thus allowing the publish pipeline to only support the new schema.
- [ x] Documentation update
> docs: update catalog json file to use new schema

- .github/settings.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .secrets.baseline
- README.md
- examples/ibm-catalog/prepared-system-solution/README.md
- examples/prepared-system/README.md
- ibm_catalog.json
- module-metadata.json
- tests/go.mod
- tests/go.sum
Please include a summary of the change and which issue is fixed. Also, please include the motivation and context for the change. List any dependencies that are required for this change.
> Merge main to sprint-6

- examples/basic/README.md
- examples/basic/variables.tf
- main.tf
- outputs.tf
- submodules/power_instance/main.tf
- submodules/power_instance/outputs.tf
Fix terraform_deprecated_index tflint rulechange.
> fix: address tflint terraform_deprecated_index rule

- ibm_catalog.json
add type spec to architecture image
- [ x] CI related update (pipeline, etc.)
> ci: fix architecture image spec in catalog manifest

- .secrets.baseline
- ibm_catalog.json
Add product label in catalog manifest and provide a complete usage string.
- [x ] Documentation update
> docs: provide complete usage string and add product label

- examples/basic/README.md
- examples/basic/variables.tf
- examples/prepared-system/README.md
- examples/prepared-system/input.tfvars
- examples/prepared-system/variables.tf
- main.tf
- module-metadata.json
- submodules/power_instance/main.tf
- submodules/power_sap_instance_init/scripts/services_init.sh
- tests/pr_test.go
- variables.tf
Please include a summary of the change and which issue is fixed. Also, please include the motivation and context for the change. List any dependencies that are required for this change.
> feat: add support for lon04 and lon06 + modify some timeouts

- submodules/power_sap_instance_init/main.tf
- submodules/power_sap_instance_init/scripts/services_init.sh
Please include a summary of the change and which issue is fixed. Also, please include the motivation and context for the change. List any dependencies that are required for this change.
> feat: Lock power ansible galaxy solution to a specific version

- .github/workflows/ci.yml
- .github/workflows/release.yml
update pipeline version to unblock pipeline
---
> ci: update pipeline version to unblock pipeline

- .secrets.baseline
- README.md
- examples/basic/README.md
- examples/basic/main.tf
- examples/basic/variables.tf
- examples/basic/version.tf
- examples/ibm-catalog/prepared-system-solution/README.md
- examples/ibm-catalog/prepared-system-solution/version.tf
- examples/prepared-system/README.md
- examples/prepared-system/version.tf
- ibm_catalog.json
- module-metadata.json
- submodules/initial_validation/README.md
- submodules/initial_validation/versions.tf
- submodules/power_attach_private_network/README.md
- submodules/power_attach_private_network/versions.tf
- submodules/power_create_private_network/README.md
- submodules/power_create_private_network/versions.tf
- submodules/power_instance/README.md
- submodules/power_instance/versions.tf
- submodules/power_sap_instance_init/README.md
- submodules/power_sap_instance_init/versions.tf
- version.tf
TF version Upgrade to 1.3 and Provider Upgrade to 1.5
---
> Provider upgrade and TF Upgrade to 1.3

- examples/ibm-catalog/deployable-architectures/sap-ready-to-go/README.md
- ibm_catalog.json
remove the ac-4 scan profile from catalog.json file
> docs: remove ac-4 scan profile

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .secrets.baseline
- ibm_catalog.json
- renovate.json
- tests/go.mod
- tests/go.sum
> merge main to dev

- .secrets.baseline
- ibm_catalog.json
This is a slimmed down version of the configuration of the deployment variables. Removed were the duplicate information that is also in the variables.tf file which should be the source of truth. Configuration was retained for all the variables so that their order would be preserved in the catalog consumption UI.
Descriptions, default values, etc. to come from the variables.tf file.
- [x ] Documentation update
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents …
> docs: remove duplicate info from variables in manifest

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .secrets.baseline
- ibm_catalog.json
- tests/go.mod
- tests/go.sum
> merge: main to dev

- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
> docs: Update deploy-arch-ibm-pvs-sap-ready-to-go.md

- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
merging this https://github.com/terraform-ibm-modules/terraform-ibm-powervs-sap/pull/314 in Current PR
---
> docs: addition of links and download

- examples/ibm-catalog/deployable-architectures/sap-ready-to-go/main.tf
Rename nfs_path to nfs_host_or_ip_path according to infra repo output
---
> fix: infra nfs variable rename

- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
Add `production` flag in reference architecture markdown file.
---
> add metadata to reference architecture

- ibm_catalog.json
Try to load dependencies from internal infra solution
---
> docs: test with internal id

- module-metadata.json
- submodules/power_instance/README.md
- submodules/power_instance/variables.tf
- submodules/power_sap_instance_init/main.tf
Reboot wait for all target Ips (HANA Vm, 1:N NW vms)
---
> fix: reboot wait count for target ips

- ibm_catalog.json
Updates to catalo_json file: Add description, dropdown widget for os_image_distro, upgrade to sccv3 compliance
---
> docs: list dropdown in catalog

- examples/terraform-registry/sap-ready-to-go/outputs.tf
- submodules/terraform_templates/services_init.sh.tftpl
Update the services_init.sh.tfpl file to handle OS registration on SLES efficiently. Source the /etc/bash.bashrc helps in mitigating the issue
---
> fix: os registration sles

- submodules/terraform_templates/install_packages.sh.tftpl
Remove $ in script to install awscli package on intel machine
---
> fix: zypper install awscli

- solutions/ibm-catalog/deployable-architectures/sap-ready-to-go/variables.tf
fixed     condition     = (upper(var.os_image_distro) == "RHEL" || upper(var.os_image_distro) == "SLES"). Was set to a different variable
If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to …
> fix: validation

- .github/settings.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- README.md
- migrate to v2 pipeline
- remove build status badge (no longer applicable with new pipeline)
NOTE: This PR will have to be force merged, as pipeline will not run until it is merged to main branch
If the CI pipeline doesn't run when you create the PR, …
> ci: migrate to v2 pipeline

- submodules/power_instance/main.tf
Extend timeout for power instance creation from 30m to 50m. 
Run the CI pipeline when the PR is ready for review and you …
> fix: extend timeout for pi instance to 50m

- solutions/sap-ready-to-go/README.md
- solutions/sap-ready-to-go/catalogValidationValues.json.template
- solutions/sap-ready-to-go/main.tf
- solutions/sap-ready-to-go/outputs.tf
- solutions/sap-ready-to-go/variables.tf
- solutions/sap-ready-to-go/version.tf
If the CI pipeline doesn't run when you …
> feat: add standard solution

- solutions/ibm-catalog/sap-ready-to-go/main.tf
- solutions/sap-ready-to-go/main.tf
If the CI pipeline doesn't run when you …
> fix: regions

- submodules/terraform_templates/ansible_exec.sh.tftpl
fix ansible version. Downgrade to 1.0.10
Run the CI pipeline when the PR is ready for review and you expect tests to …
> fix: ansible version

- solutions/ibm-catalog/sap-ready-to-go/README.md
- solutions/ibm-catalog/sap-ready-to-go/main.tf
- solutions/ibm-catalog/sap-ready-to-go/outputs.tf
- solutions/ibm-catalog/sap-ready-to-go/version.tf
- solutions/sap-ready-to-go/main.tf
- solutions/sap-ready-to-go/module/README.md
- solutions/sap-ready-to-go/module/main.tf
- solutions/sap-ready-to-go/module/outputs.tf
- solutions/sap-ready-to-go/module/variables.tf
- solutions/sap-ready-to-go/module/version.tf
- solutions/sap-ready-to-go/outputs.tf
- solutions/sap-ready-to-go/version.tf
If the CI pipeline doesn't run when you …
> feat: module

- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
Switch architecture file to production ready
Run the CI pipeline when the PR is ready for review and you expect tests to …
> docs: make production ready

- ibm_catalog.json
Fix label name
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR …
> docs: fix label name

- .github/settings.yml
- .secrets.baseline
- ibm_catalog.json
- add repo topics
- remove `usage_template` from catalog manifest. DAs are not designed to be embedded into part of another DA solution, they are designed to be the top level solution and not called from any higher level. So in this PR, I am removing the `usage_template` from the DA manifest which means the DA will no long show the `Embed code` section in the UI:
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging …
> ci: add repo topics + remove usage_template from catalog manifest

- .catalog-onboard-pipeline.yaml
- .releaserc
onboard to new pipeline
```
/run pipeline
```
> ci: onboard to new catalog pipeline

- .catalog-onboard-pipeline.yaml
- README.md
- modules/pi-sap-system-type1/README.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
- solutions/e2e/README.md
- solutions/ibm-catalog/sap-ready-to-go/README.md
- solutions/ibm-catalog/sap-s4hana-bw4hana/README.md
- solutions/sap-ready-to-go/README.md
update broken links in Docs
```
/run pipeline
```
> docs: update broken links in Docs

- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
update for cloud docs
```
/run pipeline
```
> docs: update for cloud docs

- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
> docs: update for cloud docs ibm

- ibm_catalog.json
- modules/pi-sap-system-type1/main.tf
- solutions/e2e/provider.tf
- solutions/ibm-catalog/sap-ready-to-go/provider.tf
- solutions/ibm-catalog/sap-s4hana-bw4hana/provider.tf
- solutions/sap-ready-to-go/provider.tf
Enable deployments in  WDC06 PER DC
```
/run pipeline
```
> feat: enable wdc06 PER DC deployments

- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
Update architecture version for cloud docs
```
/run pipeline
```
> docs: update versions for cloud docs

- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
update toc version for ibm cloud docs
```
/run pipeline
```
> docs: update toc version for ibm cloud docs

- ibm_catalog.json
- modules/pi-sap-system-type1/README.md
- modules/pi-sap-system-type1/version.tf
- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
- solutions/e2e/README.md
- solutions/e2e/main.tf
- solutions/e2e/version.tf
- solutions/ibm-catalog/sap-ready-to-go/README.md
- solutions/ibm-catalog/sap-ready-to-go/version.tf
- solutions/ibm-catalog/sap-s4hana-bw4hana/README.md
- solutions/ibm-catalog/sap-s4hana-bw4hana/version.tf
upgrade ibm provider version to 1.60.0 and infra version to v4.0.0
```
/run pipeline
```
> feat: upgrade tf version to 1.60.0 and infra version to v4.0.0

- ibm_catalog.json
- modules/pi-sap-system-type1/main.tf
> ci: change pi_network_jumbo to pi_network_mtu as it is depreciated

- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
> docs: update toc in reference architecture

- README.md
- modules/pi-sap-system-type1/README.md
- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
- solutions/e2e/README.md
- solutions/ibm-catalog/sap-ready-to-go/README.md
- solutions/ibm-catalog/sap-s4hana-bw4hana/README.md
- solutions/sap-ready-to-go/README.md
- tests/README.md
**LLM-Assisted Editing Enhancement**
To make the most of your modifications or further developments, it's advisable to use the specific branch from which this Pull Request (PR) originates. This will ensure you have a solid and up-to-date foundation for your tweaks and enhancements.
_Using [Markdown LLM Corrector](https://github.com/vburckhardt/markdown-llm-corrector)._
> Update markdown documents

- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
> ci: toc.yaml update

- ibm_catalog.json
Required fixes for ibm_catalog.json
```
/run pipeline
```
> ci: fix for ibm_catalog.json

- tests/common-go-assets/cloudinfo-region-power-prefs.yaml
- tests/pr_test.go
add regions prefs.yaml file
```
/run pipeline
```
> ci: add regions prefs.yaml file

- ibm_catalog.json
- modules/pi-sap-system-type1/README.md
- modules/pi-sap-system-type1/main.tf
- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
- solutions/e2e/README.md
- solutions/e2e/main.tf
PER support for dal12
```
/run pipeline
```
> feat: PER support for dal12

- ibm_catalog.json
- modules/pi-sap-system-type1/README.md
- modules/pi-sap-system-type1/main.tf
- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
- solutions/e2e/README.md
- solutions/e2e/main.tf
switch sao01 to per
```
/run pipeline
```
> feat: switch sao01 to per

- modules/pi-hana-storage-config/main.tf
- modules/pi-sap-system-type1/main.tf
recreate storage sizing according to best tiers and reduce prizing
```
/run pipeline
```
> fix: recreate storage sizing according to best tiers and reduce prizing for various memory size

- ibm_catalog.json
- modules/pi-sap-system-type1/README.md
- modules/pi-sap-system-type1/main.tf
- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
- solutions/e2e/README.md
- solutions/e2e/main.tf
switch syd04 DC to PER DC
```
/run pipeline
```
> feat: switch syd04 DC to PER DC

- README.md
- solutions/e2e/README.md
- solutions/e2e/main.tf
- solutions/e2e/variables.tf
- solutions/ibm-catalog/sap-ready-to-go/README.md
- solutions/ibm-catalog/sap-ready-to-go/variables.tf
- solutions/ibm-catalog/sap-s4hana-bw4hana/variables.tf
Fix ssh private key var description. Not required to enter in here doc format anymore for catalog usage
```
/run pipeline
```
> ci: update vars description

- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
> docs: set prod to true

- ibm_catalog.json
- modules/ansible/ansible_node_packages.sh
- modules/pi-sap-system-type1/README.md
- modules/pi-sap-system-type1/main.tf
- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
- solutions/e2e/README.md
- solutions/e2e/main.tf
ansible role version 2.1.1 fixes SLES init
```
/run pipeline
```
> fix: ansible role version 2.1.1 fixes SLES init

- modules/ansible/templates-ansible/hanadb/playbook-sap-hana-install.yml.tftpl
- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
add a task to install locale en-US required for hana installation
```
/run pipeline
```
> fix: add a task to install locale en-US for hana installation

- ibm_catalog.json
Include mad02 DC and remove mon01 and lon04 Non Per DCs
```
/run pipeline
```
> chore: update DC list

- modules/ansible/main.tf
- solutions/ibm-catalog/sap-s4hana-bw4hana/main.tf
> fix: ansible playbook vars for playbook

- ibm_catalog.json
- modules/pi-sap-system-type1/README.md
- modules/pi-sap-system-type1/main.tf
- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
- solutions/e2e/README.md
- solutions/e2e/version.tf
- solutions/ibm-catalog/sap-ready-to-go/README.md
- solutions/ibm-catalog/sap-ready-to-go/version.tf
- solutions/ibm-catalog/sap-s4hana-bw4hana/README.md
- solutions/ibm-catalog/sap-s4hana-bw4hana/version.tf
- solutions/sap-ready-to-go/README.md
- solutions/sap-ready-to-go/version.tf
> fix: upgrade TF provider and fix ansible vault for linux instance init

- solutions/ibm-catalog/sap-ready-to-go/README.md
- solutions/ibm-catalog/sap-ready-to-go/variables.tf
> chore: update description for ansible_vault_password

- ibm_catalog.json
- modules/ansible/versions.tf
- reference-architectures/sap-ready-to-go/deploy-arch-ibm-pvs-sap-ready-to-go.md
- reference-architectures/sap-s4hana-bw4hana/deploy-arch-ibm-pvs-sap-s4hana-bw4hana.md
update toc version
```
/run pipeline
```
> chore(docs): update toc version

- solutions/e2e/README.md
- solutions/e2e/main.tf
- solutions/e2e/version.tf
- solutions/ibm-catalog/sap-ready-to-go/README.md
- solutions/ibm-catalog/sap-ready-to-go/version.tf
- solutions/ibm-catalog/sap-s4hana-bw4hana/README.md
- solutions/ibm-catalog/sap-s4hana-bw4hana/version.tf
- solutions/sap-ready-to-go/README.md
- solutions/sap-ready-to-go/version.tf
- tests/pr_test.go
SKIP UPGRADE TEST: network retry
```
/run pipeline
```
> chore: upgrade tf provider
